FROM logstash:5.0.0
MAINTAINER Daniel Wei <danielwii0326@gmail.com>

RUN /usr/share/logstash/bin/logstash-plugin install logstash-output-syslog

ADD . /config-dir/

ADD https://raw.githubusercontent.com/danielwii/docker_base_scripts/master/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["logstash", "-f", "/config-dir/logstash.conf"]
